repos:
- repo: local
  hooks:
  - id: spec-update
    name: Require spec updates for code changes
    entry: uv run python scripts/check_spec_updated.py
    language: system
    pass_filenames: false
  - id: mypy-strict
    name: mypy strict checking
    entry: uv run mypy --strict
    language: system
    types: [python]
    pass_filenames: false
  - id: flake8-lint
    name: Enforce comprehensive flake8 rules
    entry: uv run flake8
    language: system
    types: [python]
    pass_filenames: false
