version: '3.8'
services:
  autoresearch:
    build:
      context: .
      args:
        BASE_IMAGE: ${BASE_IMAGE:-python:3.12-slim}
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uv run uvicorn autoresearch.api:app --host 0.0.0.0 --port 8000
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
