site_name: Autoresearch
nav:
  - Getting Started: getting_started.md
  - Configuration: configuration.md
  - Agents: agents_overview.md
  - Agent Communication: agent_communication.md
  - Storage: storage.md
  - Orchestration: orchestration.md
  - API Usage: api.md
  - Advanced Usage: advanced_usage.md
  - Deployment: deployment.md
  - FAQ: faq.md
  - Agent System: agent_system.md
  - Component Interactions: component_interactions.md
  - Message Brokers: message_brokers.md
  - API Reference:
    - Overview: api_reference/index.md
    - Agents: api_reference/agents.md
    - Orchestration: api_reference/orchestration.md
    - Storage: api_reference/storage.md
    - LLM: api_reference/llm.md
    - Search: api_reference/search.md
    - Config: api_reference/config.md
  - Contributing: contributing.md
  - Requirements: requirements.md
  - Specification: specification.md
  - Plan: plan.md
  - Pseudocode: pseudocode.md
  - Requirements Traceability Matrix: requirements_traceability_matrix.md
  - Testing Guidelines: testing_guidelines.md
  - Troubleshooting:
    - Multiprocessing Resource Tracker: multiprocessing_resource_tracker.md
markdown_extensions:
  - toc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: false
            show_category_heading: true
            show_if_no_docstring: false
            heading_level: 2
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
