[project]
name = "autoresearch"
version = "0.1.0"
description = ""
authors = [
    {name = "Caitlyn O'Hanna",email = "caitlyn.ohanna@gmail.com"}
]
readme = "README.md"
requires-python = "<3.13,>=3.11"
packages = [{include = "autoresearch", from = "src"}]
dependencies = [
    "structlog (>=25.3.0,<26.0.0)",
    "dspy-ai (>=2.6.24,<3.0.0)",
    "python-dotenv (>=1.1.0,<2.0.0)",
    "langgraph (>=0.4.5,<0.5.0)",
    "langchain-community (>=0.3.24,<0.4.0)",
    "typer (>=0.15.4,<0.16.0)",
    "chromadb (>=1.0.9,<2.0.0)",
    "mcp[cli] (>=1.9.0,<2.0.0)",
    "pydantic (>=2.11.4,<3.0.0)",
    "pydantic-settings (>=2.9.1,<3.0.0)",
    "requests (>=2.32.3,<3.0.0)",
    "responses (>=0.25.7,<0.26.0)",
    "networkx (>=3.4.2,<4.0.0)",
    "duckdb (>=1.2.2,<2.0.0)",
    "rdflib (>=7.1.4,<8.0.0)",
    "fastapi (>=0.115.0,<0.116.0)",
    "loguru (>=0.7.2,<0.8.0)",
    "prometheus_client (>=0.20.0,<0.21.0)"
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-bdd = "^8.1.0"
pytest-cov = "^6.1.1"
flake8 = "^7.2.0"
mypy = "^1.16.0"
tomli-w = "^1.2.0"
types-requests = "^2.32.0"
types-networkx = "^3.4.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--maxfail=1 --disable-warnings -q --cov=src --cov=tests --cov-report=xml --cov-report=term-missing"
testpaths = ["tests/unit", "tests/integration", "tests/behavior"]
markers = [
    "behavior: mark behavior (BDD) tests",
    "integration: mark integration tests",
    "unit: mark unit tests"
]

