version: '3'

tasks:
  unit:
    cmds:
      - pytest -q tests/unit
    desc: "Run unit tests"

  integration:
    cmds:
      - pytest -q integration
    desc: "Run integration tests"

  behavior:
    cmds:
      - pytest -q tests/behavior
    desc: "Run BDD (behavior) tests"

  test:
    deps: [unit, integration, behavior]
    desc: "Run all tests"

  coverage:
    cmds:
      - pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml --cov-report=term-missing tests
    desc: "Run full test suite with coverage reporting"

  clean:
    cmds:
      - find . -type d -name '__pycache__' -exec rm -rf {} +
      - find . -type d -name '.mypy_cache' -exec rm -rf {} +
    desc: "Remove Python cache directories"

