version: '3'

set:
  - e

vars:
  COVERAGE_THRESHOLD: 90

tasks:
  install:
    cmds:
      - uv sync --extra dev-minimal
    desc: "Initialize development environment"
  check-env:
    cmds:
      - uv run python scripts/check_env.py
      - >
          uv run python -c "import pytest_httpx" 2>/dev/null ||
          echo "Warning: pytest-httpx missing; install with 'task install' or 'uv sync --extra dev-minimal'."
      - >
          uv run python -c "import tomli_w" 2>/dev/null ||
          echo "Warning: tomli-w missing; install with 'task install' or 'uv sync --extra dev-minimal'."
      - >
          uv run python -c "import redis" 2>/dev/null ||
          echo "Warning: redis missing; install with 'task install' or 'uv sync --extra dev-minimal'."
    desc: "Validate required tool versions"
  check:
    deps: [check-env]
    # Minimal validation for quick feedback. Skips slow tests and scenarios
    # requiring optional UI (`.[ui]`) or VSS (`.[vss]`) extras.
    cmds:
      - uv run flake8 src tests
      - uv run mypy src
      - uv run python scripts/check_spec_tests.py
      - uv run pytest tests/unit -q
      - >
          uv run pytest tests/integration -m "not slow and not requires_ui and
          not requires_vss and not requires_distributed" -q
      - uv run pytest --rootdir=. tests/behavior -q
    desc: "Run lint, type check, and fast tests"
  unit:
    cmds:
      - uv run pytest tests/unit -q
    desc: "Run unit tests with uv"

  integration:
    cmds:
      - >
          uv run pytest tests/integration -m "not slow and not requires_ui and
          not requires_vss and not requires_distributed" -q
    desc: "Run integration tests without slow/UI/VSS scenarios with uv"

  behavior:
    cmds:
      - uv run pytest --rootdir=. tests/behavior -q
    desc: "Run BDD (behavior) tests with uv"

  test:
    deps: [test:unit, test:integration, test:behavior]
    desc: "Run all tests"

  test:unit:
    cmds:
      - uv run pytest tests/unit -q
    desc: "Run unit tests with uv"

  test:integration:
    cmds:
      - >
          uv run pytest tests/integration -m "not slow and not requires_ui and
          not requires_vss and not requires_distributed" -q
    desc: "Run integration tests without slow/UI/VSS scenarios with uv"

  test:behavior:
    cmds:
      - uv run pytest --rootdir=. tests/behavior -q
    desc: "Run BDD (behavior) tests with uv"

  test:all:
    # Full run before releases. Includes slow tests but continues to skip
    # UI and VSS scenarios unless the `ui` or `vss` extras are installed.
    cmds:
      - >
          uv run pytest -m 'not requires_ui and not requires_vss and not
          requires_distributed' -q
    desc: "Run all tests including slow ones (UI/VSS scenarios skipped)"

  test:fast:
    # Minimal test run used for rapid iteration. Excludes slow tests and any
    # requiring UI (`.[ui]`) or VSS (`.[vss]`) extras.
    cmds:
      - >
          uv run pytest -m 'not slow and not requires_ui and not requires_vss
          and not requires_distributed'
    desc: "Run tests excluding slow/UI/VSS scenarios with uv"

  test:slow:
    # Executes only slow tests while skipping UI (`.[ui]`) and VSS (`.[vss]`)
    # scenarios unless those extras are installed.
    cmds:
      - >
          uv run pytest -m 'slow and not requires_ui and not requires_vss and
          not requires_distributed'
    desc: "Run slow tests excluding UI/VSS scenarios with uv"

  test:benchmarks:
    cmds:
      - uv run pytest tests/integration/test_query_performance_benchmark.py -q
    desc: "Run performance benchmark tests with uv"

  coverage:
    cmds:
      - uv run pytest tests/unit --cov=src --cov-report=term-missing --cov-append
      - >
          uv run pytest tests/integration -m 'not requires_ui and not requires_vss
          and not requires_distributed' --cov=src --cov-report=term-missing
          --cov-append
      - uv run pytest --rootdir=. tests/behavior --cov=src --cov-report=xml --cov-report=term-missing \
          --cov-append
      - uv run coverage report --fail-under={{.COVERAGE_THRESHOLD}}
      - uv run python scripts/check_token_regression.py --threshold 5
    desc: "Run full test suite with coverage reporting"

  verify:
    deps: [check-env]
    # Coverage-enabled check before committing. Still skips slow tests and
    # optional UI (`.[ui]`) and VSS (`.[vss]`) scenarios to keep runtime
    # reasonable.
    cmds:
      - uv run flake8 src tests
      - uv run mypy src
      - uv run python scripts/check_spec_tests.py
      - uv run pytest tests/unit --cov=src --cov-report=term-missing --cov-append
      - >
          uv run pytest tests/integration -m "not slow and not requires_ui and
          not requires_vss and not requires_distributed" \
          --cov=src --cov-report=term-missing --cov-append
      - uv run pytest --rootdir=. tests/behavior --cov=src --cov-report=xml --cov-report=term-missing \
          --cov-append
      - uv run coverage report --fail-under={{.COVERAGE_THRESHOLD}}
      - uv run python scripts/check_token_regression.py --threshold 5
    desc: "Run linting, type checks and fast tests with coverage"

  clean:
    cmds:
      - find . -type d -name '__pycache__' -exec rm -rf {} +
      - find . -type d -name '.mypy_cache' -exec rm -rf {} +
    desc: "Remove Python cache directories"

  bump-version:
    cmds:
      - uv run python scripts/bump_version.py {{.CLI_ARGS}}
    desc: "Update project version numbers"

  check-baselines:
    cmds:
      - uv run python scripts/check_token_regression.py --threshold 5
    desc: "Validate token usage against baselines with uv"

  wheels:
    deps: [wheel-linux, wheel-windows, wheel-macos]
    desc: "Build wheels for all platforms"

  wheel-linux:
    cmds:
      - uv run cibuildwheel --platform linux --output-dir dist/linux
    desc: "Build Linux wheel with uv"

  wheel-windows:
    cmds:
      - uv run cibuildwheel --platform windows --output-dir dist/windows
    desc: "Build Windows wheel with uv"

  wheel-macos:
    cmds:
      - uv run cibuildwheel --platform macos --output-dir dist/macos
    desc: "Build macOS wheel with uv"

