version: '3'

tasks:
  unit:
    cmds:
      - uv run pytest tests/unit -q
    desc: "Run unit tests with uv"

  integration:
    cmds:
      - uv run pytest tests/integration -m "not slow" -q
    desc: "Run integration tests with uv"

  behavior:
    cmds:
      - uv run pytest tests/behavior -q
    desc: "Run BDD (behavior) tests with uv"

  test:
    deps: [test:unit, test:integration, test:behavior]
    desc: "Run all tests"

  test:unit:
    cmds:
      - uv run pytest tests/unit -q
    desc: "Run unit tests with uv"

  test:integration:
    cmds:
      - uv run pytest tests/integration -m "not slow" -q
    desc: "Run integration tests with uv"

  test:behavior:
    cmds:
      - uv run pytest tests/behavior -q
    desc: "Run BDD (behavior) tests with uv"

  test:all:
    cmds:
      - uv run pytest -q
    desc: "Run the entire test suite including slow tests with uv"

  test:fast:
    cmds:
      - uv run pytest -m 'not slow'
    desc: "Run tests excluding those marked slow with uv"

  test:slow:
    cmds:
      - uv run pytest -m slow
    desc: "Run only tests marked as slow with uv"

  test:benchmarks:
    cmds:
      - uv run pytest tests/integration/test_query_performance_benchmark.py -q
    desc: "Run performance benchmark tests with uv"

  coverage:
    cmds:
      - uv run pytest tests/unit --cov=src --cov-report=term-missing --cov-append
      - uv run pytest tests/integration --cov=src --cov-report=term-missing --cov-append
      - uv run pytest tests/behavior --cov=src --cov-report=xml --cov-report=term-missing
    desc: "Run full test suite with coverage reporting"

  verify:
    cmds:
      - uv run flake8 src tests
      - uv run mypy src
      - uv run pytest tests/unit --cov=src --cov-report=term-missing --cov-append
      - uv run pytest tests/integration -m "not slow" --cov=src --cov-report=term-missing --cov-append
      - uv run pytest tests/behavior --cov=src --cov-report=xml --cov-report=term-missing
    desc: "Run linting, type checks and all test suites with coverage"

  clean:
    cmds:
      - find . -type d -name '__pycache__' -exec rm -rf {} +
      - find . -type d -name '.mypy_cache' -exec rm -rf {} +
    desc: "Remove Python cache directories"

  check-baselines:
    cmds:
      - uv run python scripts/check_token_regression.py --threshold 5
    desc: "Validate token usage against baselines with uv"

  wheels:
    deps: [wheel-linux, wheel-windows, wheel-macos]
    desc: "Build wheels for all platforms"

  wheel-linux:
    cmds:
      - uv run cibuildwheel --platform linux --output-dir dist/linux
    desc: "Build Linux wheel with uv"

  wheel-windows:
    cmds:
      - uv run cibuildwheel --platform windows --output-dir dist/windows
    desc: "Build Windows wheel with uv"

  wheel-macos:
    cmds:
      - uv run cibuildwheel --platform macos --output-dir dist/macos
    desc: "Build macOS wheel with uv"

