version: '3'

tasks:
  unit:
    cmds:
      - poetry run pytest tests/unit -q
    desc: "Run unit tests"

  integration:
    cmds:
      - poetry run pytest tests/integration -m "not slow" -q
    desc: "Run integration tests"

  behavior:
    cmds:
      - poetry run pytest tests/behavior -q
    desc: "Run BDD (behavior) tests"

  test:
    deps: [test:unit, test:integration, test:behavior]
    desc: "Run all tests"

  test:unit:
    cmds:
      - poetry run pytest tests/unit -q
    desc: "Run unit tests"

  test:integration:
    cmds:
      - poetry run pytest tests/integration -m "not slow" -q
    desc: "Run integration tests"

  test:behavior:
    cmds:
      - poetry run pytest tests/behavior -q
    desc: "Run BDD (behavior) tests"

  test:all:
    cmds:
      - poetry run pytest -q
    desc: "Run the entire test suite including slow tests"

  test:fast:
    cmds:
      - poetry run pytest -m 'not slow'
    desc: "Run tests excluding those marked slow"

  test:slow:
    cmds:
      - poetry run pytest -m slow
    desc: "Run only tests marked as slow"

  coverage:
    cmds:
      - pytest --maxfail=1 --disable-warnings -q --cov=src --cov-report=xml --cov-report=term-missing tests
    desc: "Run full test suite with coverage reporting"

  clean:
    cmds:
      - find . -type d -name '__pycache__' -exec rm -rf {} +
      - find . -type d -name '.mypy_cache' -exec rm -rf {} +
    desc: "Remove Python cache directories"

  check-baselines:
    cmds:
      - poetry run python scripts/check_token_regression.py --threshold 5
    desc: "Validate token usage against baselines"

  wheels:
    deps: [wheel-linux, wheel-windows, wheel-macos]
    desc: "Build wheels for all platforms"

  wheel-linux:
    cmds:
      - poetry run cibuildwheel --platform linux --output-dir dist/linux
    desc: "Build Linux wheel"

  wheel-windows:
    cmds:
      - poetry run cibuildwheel --platform windows --output-dir dist/windows
    desc: "Build Windows wheel"

  wheel-macos:
    cmds:
      - poetry run cibuildwheel --platform macos --output-dir dist/macos
    desc: "Build macOS wheel"

