name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry and Task
        run: |
          python -m pip install poetry
          curl -sL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin
      - name: Install dependencies
        run: |
          poetry env use $(which python)
          poetry install --with dev --all-extras
      - name: Run full test suite
        run: task test:all
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
