name: CI (Python 3.12)
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Verify Python version
        run: |
          python - <<'EOF'
          import sys
          major, minor = sys.version_info[:2]
          assert (major == 3 and minor >= 12), f"Python 3.12 or newer required, got {major}.{minor}"
          EOF
      - name: Install uv
        run: python -m pip install uv
      - name: Install dependencies
        run: uv pip sync uv.lock
      - name: Lint
        run: uv run flake8 src tests
      - name: Type check
        run: uv run mypy src
      - name: Test
        run: uv run pytest -q
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
