name: Build wheels

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Poetry
        run: python -m pip install poetry
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
      - uses: actions/upload-artifact@v4
        with:
          path: wheelhouse/*.whl
          name: wheels-${{ matrix.os }}
