# Minimal Autoresearch configuration using LM Studio and Serper
[core]
llm_backend = "lmstudio"
loops = 2
reasoning_mode = "dialectical"
default_model = "mistral"

[search]
backends = ["serper"]
max_results_per_query = 5
hybrid_query = false
use_semantic_similarity = false
use_bm25 = true
use_source_credibility = false

[storage.duckdb]
path = "data/autoresearch.duckdb"
vector_extension = false
