[core]
llm_backend = "lmstudio"
loops = 3
tracing_enabled = false

[storage.duckdb]
path = "data/research.duckdb"
vector_extension = true
# Path to the VSS extension file for offline use
# Use the download_duckdb_extensions.py script to download the extension
# vector_extension_path = "./extensions/vss/vss.duckdb_extension"

[agent.Synthesizer]
model = "gpt-3.5-turbo"

[agent.Contrarian]
enabled = true

[agent.FactChecker]
enabled = true
