from typing import Any

class Error(Exception):
    ...

class DuckDBPyConnection:
    def __init__(self) -> None: ...
    def execute(self, *args: Any, **kwargs: Any) -> DuckDBPyConnection: ...
    def fetchall(self) -> list[Any]: ...
    def fetchone(self) -> Any | None: ...
    def close(self) -> None: ...
    def __enter__(self) -> DuckDBPyConnection: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: object | None,
    ) -> bool | None: ...


def connect(*args: Any, **kwargs: Any) -> DuckDBPyConnection: ...
