from typing import Any, Callable, Type

class BoundLogger:
    def __getattr__(self, name: str) -> Callable[..., None]: ...

def get_logger(*args: Any, **kwargs: Any) -> BoundLogger: ...

def configure(*args: Any, **kwargs: Any) -> None: ...

def make_filtering_bound_logger(level: Any) -> Type[BoundLogger]: ...
