from __future__ import annotations

from typing import Any, Protocol

__all__ = ["DataFrame", "col"]


class DataFrame:
    def __init__(self, data: Any) -> None: ...

    def sort(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def select(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def item(self, *args: Any, **kwargs: Any) -> Any: ...

    def pivot(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def copy(self) -> DataFrame: ...

    def melt(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def reset_index(self, *args: Any, **kwargs: Any) -> DataFrame: ...


class Expr(Protocol):
    def mean(self) -> Expr: ...


def col(name: str) -> Expr: ...
