from __future__ import annotations

from typing import Any, Iterable

__all__ = ["DataFrame", "Series"]


class DataFrame:
    def __init__(self, data: Any, *args: Any, **kwargs: Any) -> None: ...

    def set_index(self, keys: Any) -> DataFrame: ...

    def __getitem__(self, key: Any) -> Any: ...

    def __setitem__(self, key: Any, value: Any) -> None: ...

    def __iter__(self) -> Iterable[Any]: ...

    def copy(self) -> DataFrame: ...

    def pivot(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def reset_index(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    def melt(self, *args: Any, **kwargs: Any) -> DataFrame: ...

    columns: Any


class Series:
    def __init__(self, data: Any, *args: Any, **kwargs: Any) -> None: ...
