name: CI

# This workflow is manually triggered only.
# Run it from the Actions tab via "Run workflow" or
# via the CLI: `gh workflow run CI`.
on:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Verify Python version
        run: |
          python - <<'EOF'
          import sys
          major, minor = sys.version_info[:2]
          assert major == 3 and minor >= 12, f"Python 3.12 or newer required, got {major}.{minor}"
          EOF
      - name: Install uv
        run: python -m pip install uv
      - name: Check environment
        run: uv run python scripts/check_env.py
      - name: Install dependencies
        run: uv pip sync uv.lock
      - name: Install extras
        run: uv pip install -e '.[full,parsers,git,llm,dev]'
      - name: Run task verify
        run: uv run task verify
      - name: Run tests with coverage
        run: uv run pytest --cov=src
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data
          path: .coverage
